### ISSUE TITLE
FE error

### ISSUE THREAD

**Issue by gomjunho** [gomjunho/SampleRecipe#1]
npm run dev

Error: Cannot find module '../lib/polyfills'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/junholee/SampleRecipe/front/node_modules/.bin/webpack-dev-server:6:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/junholee/.npm/_logs/2019-06-13T05_32_28_851Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack@1.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/junholee/.npm/_logs/2019-06-13T05_32_28_886Z-debug.log

----------------------- error log -------------------------

**Comment by gomjunho** [comment]
[https://stackoverflow.com/questions/47115764/webpack-dev-server-not-working-cannot-find-module-lib-polyfills]

node_modules/.bin/webpack-dev-server 파일 잘못되었음. 삭제 or 이름 변경 후 재설치

npm install --save-dev webpack-dev-server
